apiVersion: v1
kind: Pod
metadata:
  name: toolkit-pod
  namespace: devops-tools
  labels:
    app: toolkit
spec:
  containers:
    - name: toolkit-container
      image: mindthump/toolkit:main
      imagePullPolicy: Never
      command: ["/bin/bash"]
      args: ["-c", "trap : TERM INT; sleep infinity & wait"]
